### ISSUE TITLE
Integrated stripe payment into wix but while testing it i am getting Charge ID - Undefined error

### ISSUE THREAD

**Issue by gatakraj** [firebase/functions-samples#639] opened 2019-11-28 06:57 UTC
I am not coder i am new to coding, i wanted to add stripe payment integration into my wix website, so i came around few videos on youtube and i decided to do myself and i integrated stripe payment into wix but while testing it i am getting Charge ID - undefined Error

below i have given my Home Page Code, Public/Frontend Code and Backend Code so please have a look and advise any help would be appreciated Thanks in advance

Home Page code -
import {createToken, encodeCard} from "public/stripeAPI.js";
import {charge} from 'backend/stripeProxy';
var payment;
export function payNow(event) {
createToken(encodeCard(createCard()))
.then((token) => {
console.log("Card token: " + token);
charge(token, payment)
.then((chargeResponse) => {
console.log("Charge ID: " + chargeResponse.id); -THIS IS CHARGE ID ERROR I AM GETTING
});
});
}
function createCard() {

return {
    "name": $w("#cname").value,
    "nuumber": $w("#cnumber").value,
    "exp_month": $w("#month").value,
    "exp_year": $w("#year").value,
    "cvc": $w("#cvc").value,
};

}

function chnageState() {
payment = {
"amount": ($w("#amt").value*100),
"currency":"INR",}
}
export function chargeCard_click(event) {
payNow(); }

FrontEnd/Public Code -
import {fetch} from 'wix-fetch';
export async function createToken(card) {
//Go to stripe.com to create a test key and replace the one in the example
const apiKey = "YOUR_API_HERE";
const response = await fetch("https://api.stripe.com/v1/tokens", {
method: 'post',
headers: {
"Content-Type": "application/x-www-form-urlencoded",
"Authorization": "Bearer " + apiKey
},
body: card
});
if (response.status >= 200 && response.status < 300) {
const json = await response.json()
return json.id;
}
const responseText = await response.text();
console.log(responseText);
return response.status;
}
export function encodeCard(card){
let encoded = "";
for (let [k, v] of Object.entries(card)) {
encoded = encoded.concat("card[", k, "]=", encodeURI(v), "&");
}
return encoded.substr(0, encoded.length - 1);
}

BackEnd Code -
import {fetch} from 'wix-fetch';
export async function charge(token,payment) {
const cart = payment;
//Go to stripe.com to create a test key and replace th eone in the example
const apiKey = "YOUR_API_HERE";
const response = await fetch("https://api.stripe.com/v1/charges", {
method: 'post',
headers: {
"Content-Type": "application/x-www-form-urlencoded",
"Authorization": "Bearer " + apiKey
},
body: encodeBody(token, cart)
});
if (response.status >= 200 && response.status < 300) {
return await response.json();
}
return await response.text();
}
function encodeBody(token, cart){
let encoded = "";
for (let [k, v] of Object.entries(cart)) {
encoded = encoded.concat(k,"=", encodeURI(v), "&");
}
encoded = encoded.concat("source=", encodeURI(token));
return encoded;
}

<img width="960" alt="Charge ID error in stripe payment in wix" src="https://user-images.githubusercontent.com/58285976/69783807-49632b00-11da-11ea-9921-b5becc4128c0.png">

**Comment by jhuleatt** [comment] 2019-12-13 18:23
closing as duplicate of #640

**Closed by jhuleatt** 2019-12-13 18:23 UTC
