### ISSUE TITLE
fcm-notifications - summaryText and style

### ISSUE THREAD

**Issue by carlosrbta** [firebase/functions-samples#51] opened 2017-03-15 12:30 UTC
Is it possible to add `summaryText` and `style` in notification?

In node-gcm:

```js
var message = new gcm.Message();
message.addData('title', 'My Title');
message.addData('message', 'My second message');
message.addData('style', 'inbox');
message.addData('summaryText', 'There are %n% notifications');
```

**Comment by jamesdaniels** [comment] 2017-03-15 22:08
closing as this is a question for the Admin SDK + not a bug with the samples, but feel free to continue discussing here

**Closed by jamesdaniels** 2017-03-15 22:08 UTC
