### ISSUE TITLE
Generate thumbnail function deploying error

### ISSUE THREAD

**Issue by harshapulikollu** [firebase/functions-samples#520] opened 2018-12-02 04:45 UTC
I tried to deploy function to generate thumbnail with help of your sample. While deploying I'm getting a `TypeError: require(...) is not a function`
` at Object.<anonymous> (D:\folder nametwo\foldername\functions\index.js:20:47)`
which corresponds to the 
`const gcs = require('@google-cloud/storage')({keyFilename: 'service-account-credentials.json'});`
in my  `index.js` file.
Bdw, I copied your sample code from `master branch` and believe no typos in there.

**Comment by samtstern** [comment] 2018-12-06 18:43
This looks like a duplicate of #478

**Comment by samtstern** [comment] 2018-12-06 18:43
It could be because there is a space in the path: `folder nametwo`

**Closed by samtstern** 2018-12-06 18:43 UTC

**Comment by harshapulikollu** [comment] 2018-12-07 09:09
nothing useful when I followed and tried to change things from the thread.

**Comment by harshapulikollu** [comment] 2018-12-07 09:38
I already tired node-8 and it's showed me some error like `unauthorized token =>` that's why I tried master and which also resulted an error. I'll update you with the error in few moments.

**Comment by harshapulikollu** [comment] 2018-12-07 09:58
@nicolasgarnier I tried node-8 branch code which is the latest and I'm ended up with the error.
```
52:82  error  Parsing error: Unexpected token =>

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

and This is the 52nd line error corresponds to
`exports.generateThumbnail = functions.storage.object().onFinalize(async (object) => {`

**Comment by nicolasgarnier** [comment] 2018-12-07 10:09
Can you check your Node version? `node --version`

**Comment by harshapulikollu** [comment] 2018-12-07 10:10
```
PS C:\Users\Harsha> node --version
v10.0.0
```

**Comment by nicolasgarnier** [comment] 2018-12-07 10:31
make sure you change all the file from the Node-8 branch, not just the code. The package.json also contains different dependencies too, make sure you copy the package.json and install the dependencies (npm install)

**Comment by harshapulikollu** [comment] 2018-12-07 11:15
After changing
 ```
"parserOptions": {
    // Required for certain syntax usages
    "ecmaVersion": 2017
},
```
in file named -
 `.eslintrc.json`
Now it's resulting new error 
`eslint --max-warnings=0 .`
which I haven't got in past. Here is full stackstrace
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ lint: `eslint --max-warnings=0 .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Harsha\AppData\Roaming\npm-cache\_logs\2018-12-07T11_13_51_053Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1
```

**Comment by harshapulikollu** [comment] 2018-12-07 11:32
I Haven't modified the `firebase.json` file now, It's already there when I initialized functions for the first time for this project as I have few cloud functions running under this project.
 You mean I can deploy the code by **commenting out or removing/deleteing** the lines I mentioned below in `firebase.json` file??!
```
"predeploy": [
      "npm --prefix \"%RESOURCE_DIR%\" run lint"
    ],
```

**Comment by harshapulikollu** [comment] 2018-12-07 11:50
@nicolasgarnier I just commented those 3 `predoploy` lines in `firebase.json` and deployed the functions and it's working as expected. Thankyou for your help and valuable time.

**Comment by nicolasgarnier** [comment] 2018-12-07 13:10
Cool :) yea it's just that the sample does not have a presubmit. But it makes sense that if you added that sample into your  own project you may have a presubmit. The presubmit just checks if the code follows lint rules. There might have been some lint issues with some of your code (it's usually just code styling issues so not that big of a deal). You can always remove the presubmit and run lint manuaky when you want to make sure it follows code styles (for that just run `npm run lint` from the fcuntions directory).

I'm glad you got it fixed!
