### ISSUE TITLE
TypeError: require(...) is not a function (imageBlur)

### ISSUE THREAD

**Issue by tjb1187** [firebase/functions-samples#500] opened 2018-10-26 02:52 UTC
Hello all, I'm trying to deploy the blur Image function but on deployment I receive an error, see below.

### How to reproduce these conditions

Install all dependencies listed in the  image-blur example.
Copy and paste code into a working firebase app index.ts file.
'firebase deploy --only functions'

returns error:
`TypeError: require(...) is not a function`

### Debug output

```
TypeError: require(...) is not a function
    at Object.<anonymous> (C:\*******\functions\lib\index.js:135:45)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at C:\Users\************\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:21:11
    at Object.<anonymous> (C:\*********\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:75:3)
```

**Screenshots**

### Expected behavior

Function deploys and blurs nudie pics

### Actual behavior

Returns error on deployment

**Comment by samtstern** [comment] 2018-12-06 18:49
This is a duplicate of #478, let's discuss there.

Also are there any spaces in the path `C:\Users\************` ?

**Closed by samtstern** 2018-12-06 18:49 UTC

**Comment by gongshoudao** [comment] 2024-09-30 05:08
same issue.


ReferenceError: require is not defined
    at file:///Users/meme/workspace/FirebaseAPI/functions/index.js:1:18
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:341:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:317:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1381:24)
    at Module._compile (node:internal/modules/cjs/loader:1503:5)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
